### PR TITLE
Add queen promotion in chess

### LINKED ISSUE #27: BUG in chess- Pawn promotion
There's a bug in chess: the pawn promotion didn't work. A pawn when reaches the first row of the opponent’s side, had to become any other chess piece – Knight, Bishop, Rook, and even a Queen (not King though)

It was perfect if it's possible to add a string "Your turn" / "Opponent turn" and that both side (even those who choose black), play at the bottom of the board

Screen

### PR DESCRIPTION
**Pull request by rafaeldamasceno**
Adds promotion of pawn into queen. Still need to deal with the message logic. Fixes #27.

### CODE REVIEW

**Comment by rafaeldamasceno** [comment]
I wanted to make the game messages work slightly better. Is there a way to send a playerless message to everyone?

**Comment by Quackster** [comment]
Excellent!

You just need to re-send the board data as far as I'm aware - without swapping the turns, the client will update the board data without anyone seeing the player 'move'.

See: ``this.broadcastMap();`` you just need to re-call that again.

**Comment by emansom** [comment]
No game logic needed there. See https://github.com/bhlangonijr/chesslib/issues/76#issuecomment-965819355

**Comment by rafaeldamasceno** [comment]
@emansom Not sure how that comment changes things.

The `board.legalMoves()` function generates all the possible moves, and then we check if the move exists in the list.

The problem stems from how the library reads the moves (and probably this comes from the way the chess notation works): we need to specify not only if the piece is moving but also promoting (the `Move` constructor is overloaded for this purpose).

If there is a white pawn on a7 and it's going to promote on the same file, the PGN for this move is "a8=X" (where X is the piece it promoted into). In most cases, it's promoting to a queen, so "a8=Q" and `new Move(Square.A7, Square.A8, Piece.WHITE_QUEEN)` in the library's code (why it needs to have the color of the promotion piece is another discussion). The issue is that "a8" by itself is not a legal move (the pawn must promote on the opposite final rank), so `new Move(Square.A7, Square.A8)` isn't a legal move either. However, this is how all moves are being built at the moment.

In any case, the current addition to the code only has enough chess insight in the sense that it knows that a given move *might* be valid if it is a promotion, so it additionally checks it if the normal move isn't valid.

**Comment by emansom** [comment]
The API and its documentation are super confusing, from spitting through their bug tracker; there's a `Move#getPromotion()` function that might be of help here.

https://github.com/bhlangonijr/chesslib/issues/26#issuecomment-685171558

**Comment by rafaeldamasceno** [comment]
@emansom You got me excited for a second. Sadly, `Move#getPromotion` is nothing but a getter for the `promotion` field. So it goes back to my previous comment: if we don't specify the promotion piece when constructing the move, we won't generate a legal move in the first place.

**Comment by emansom** [comment]
> @emansom You got me excited for a second. Sadly, `Move#getPromotion` is nothing but a getter for the `promotion` field. So it goes back to my previous comment: if we don't specify the promotion piece when constructing the move, we won't generate a legal move in the first place.

isPromoRank?

https://github.com/bhlangonijr/chesslib/blob/1.3.3/src/main/java/com/github/bhlangonijr/chesslib/Board.java#L105

**Comment by emansom** [comment]
Utilizing [kengine](https://github.com/bhlangonijr/kengine) instead may lead to less code complexity and more valid results.

https://github.com/bhlangonijr/kengine/blob/1.0.2/src/main/java/com/github/bhlangonijr/kengine/alphabeta/AlphaBetaSearch.kt#L193

https://github.com/bhlangonijr/kengine#self-play-using-integration-tests

**Comment by rafaeldamasceno** [comment]
Ah, that is a good condition for the promotion move test. But it still needs to be done as a failover, since that function seems piece agnostic (and we wouldn't want other pieces promoting 😅).

**Comment by Quackster** [comment]
So just to clarify, what exactly is the behaviour that I'm missing in Havana right now? I'm not a chess player.

**Comment by rafaeldamasceno** [comment]
In chess, when you push your pawn all the way to the opposite side of the board, you promote the pawn, i.e. the pawn becomes a stronger piece. You can choose the piece it will change into in a real game, but 99% of the time you will choose the queen, since it’s the strongest piece. It’s one of the most important mechanics of the game.

In Havana, when you try to push the pawn to the final rank, it won’t register as a valid move. Since there’s no UI to choose what piece you want, I’ve coded it so that a pawn will promote into a queen.

**Comment by Quackster** [comment]
Oh okay so technically in theory if all pawns are promoted you'll have 18 queens, I understand now. 🤣

Seems simple enough - I understand the code being pushed, thank you very much!

**Comment by Quackster** [comment]
Commenting back on this, because this feature doesn't work. Was it even tested? I cannot for the life of me get it to work.

**Comment by rafaeldamasceno** [comment]
Just tested it again after all of the chess changes and it seems it's working fine:
https://github.com/Quackster/Havana/assets/6492427/84622c92-f593-46cc-9c74-f655bff8dd56

**Comment by Quackster** [comment]
> Just tested it again after all of the chess changes and it seems it's working fine:
> 
>  Recording.2024-02-20.123144.mp4

Can you post your GamehallChess.java class?

**Comment by rafaeldamasceno** [comment]
@Quackster It's exactly the same as master. You can check it on the deploy branch of my fork which only has miscellaneous changes for deploying (domain changes, Dockerfiles, imager redirection). The commit hashes are the same for this file. It's exactly what I ran to record that video.

https://github.com/rafaeldamasceno/Havana/blob/deploy/Havana-Server/src/main/java/org/alexdev/havana/game/games/gamehalls/GameChess.java

**Pull request merged**
